name: Mirror to Codeberg

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Codeberg to SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa,ecdsa,ed25519 codeberg.org >> ~/.ssh/known_hosts

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'git@codeberg.org:denizakdemir/obsidian-tipa.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
